name: WiFi Test Build

run-name: Build wifi-test-working by @${{ github.actor }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential libstdc++-arm-none-eabi-newlib python3

    - name: Clone pico-sdk
      run: |
        git clone --depth 1 https://github.com/raspberrypi/pico-sdk.git library/pico-sdk
        cd library/pico-sdk
        git submodule update --init --depth 1 lib/btstack
        git submodule update --init --depth 1 lib/cyw43-driver
        git submodule update --init --depth 1 lib/lwip
        git submodule update --init --depth 1 lib/mbedtls

    - name: Build WiFi Test for Pico 2W
      run: |
        cd wifi-test-working
        cmake -B build -DCMAKE_BUILD_TYPE=Debug -DPICO_BOARD=pico2_w
        cmake --build build --config Debug

    - name: Archive WiFi Test Artifact
      uses: actions/upload-artifact@v4
      with:
        name: wifi-test-pico2w
        path: |
          wifi-test-working/build/*.bin
          wifi-test-working/build/*.dis
          wifi-test-working/build/*.elf
          wifi-test-working/build/*.map
          wifi-test-working/build/*.hex
          wifi-test-working/build/*.uf2
